org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8

scp.host=helios.cs.ifmo.ru
scp.port=2222
scp.user=s407960
scp.password=jhwp{8647
scp.remote.deploy.path=/home/studs/s407960/wildfly-21.0.0.Final/standalone/deployments

music.file=lib/273187__nlm__alarm-pips.wav

alt.java.home=C:/Program Files/Java/jdk-21
alt.jvm.args=-Xmx512m -Dfile.encoding=UTF-8

alt.replace.class.PointBean=PointBeanAlt
alt.replace.class.ResultsBean=ResultsBeanAlt
alt.replace.class.Point=PointAlt
alt.replace.class.PointDao=PointDaoAlt
alt.replace.variable.submitSource=submitType

diff.excluded.classes=PointBean
